version: '3'

services:
  potato:
    container_name: potato
    image: jenkins/jenkins:lts-jdk17
    ports:
      - "8080:8080"
    volumes:
    - jenkins_data:/var/jenkins_home
    - //var/run/docker.sock:/var/run/docker.sock
    - /usr/local/bin/docker:/usr/local/bin/docker

  sonarqube:
    container_name: sonarqube
    image: sonarqube:latest
    ports:
      - "9000:9000"
    
  
  nexus:
    container_name: nexus
    image: sonatype/nexus3:latest
    ports:
      - "8081:8081"
     

volumes:
  jenkins_data:

networks:
  my_network:
    driver: bridge  
